### ISSUE TITLE
cleanup and document the repo

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/portfolio_simulations#12]
## Idea

The repo is mostly well-organized at this point, but I want to go through and make sure everything is as simple as possible. Also, grab a few tasks along the way.

--- 

**Tasks:**
- [x] Arbitrageur completes the other swap leg.
- [x] Add in depth Cargo doc documentation.
- [x] Add in-line comments where needed.
- [x] Add explainer in markdown format.
